# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Permalinks
permalink:           pretty

# Setup
title:               Daniel Coo
tagline:             Music and CS
description:         Words about music and computer science
url:                 danielcoo.xyz
paginate:            1
paginate_path:       /:num
baseurl:             ''

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Daniel Coo
  url:               ""
  email:             danieljohncoo@gmail.com

# Custom vars
version:             1.0.0
repository_url:      https://github.com/DC00/dc00.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
